version: "3.8"

services:
  mysql:
    image: mysql:8.3
    container_name: mireservafit_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mireservafit_bd
      MYSQL_USER: fit_user
      MYSQL_PASSWORD: fit123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./database/seed_data.sql:/docker-entrypoint-initdb.d/02_seed_data.sql
    restart: unless-stopped

volumes:
  mysql_data: