services:
  app:
    image: mcr.microsoft.com/devcontainers/java:21
    volumes:
      - ..:/workspaces/mireservafit-mvp:cached
    working_dir: /workspaces/mireservafit-mvp
    command: sleep infinity
    depends_on:
      - mysql
    environment:
      DB_URL: jdbc:mysql://mysql:3306/mireservafit_bd?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      DB_USERNAME: fit_user
      DB_PASSWORD: fit123
    ports:
      - "8080:8080"

  mysql:
    image: mysql:8.3
    container_name: mireservafit_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mireservafit_bd
      MYSQL_USER: fit_user
      MYSQL_PASSWORD: fit123
      TZ: UTC
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      # subimos a la ra√≠z con ../
      - ../database/schema.sql:/docker-entrypoint-initdb.d/01_schema.sql:ro
      - ../database/seed_data.sql:/docker-entrypoint-initdb.d/02_seed_data.sql:ro
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data: